#!/bin/python3
import yt_dlp
import sys
import os
import json
import sqlite3
import shutil
from pathlib import Path

def get_chrome_cookies():
    """Extract YouTube cookies from Chrome browser"""
    # Chrome cookie database path varies by OS
    if sys.platform == "win32":
        # Windows
        cookie_path = os.path.join(os.environ['LOCALAPPDATA'],
                                 "Google", "Chrome", "User Data", "Default", "Cookies")
    elif sys.platform == "darwin":
        # macOS
        cookie_path = os.path.expanduser('~/Library/Application Support/Google/Chrome/Default/Cookies')
    else:
        # Linux
        cookie_path = os.path.expanduser('~/.config/google-chrome/Default/Cookies')

    if not os.path.exists(cookie_path):
        print(f"Chrome cookies not found at {cookie_path}")
        print("Please make sure Chrome is installed and you've logged into YouTube")
        return None

    # Copy the cookies file to avoid locking issues
    temp_cookie = "cookies_temp.db"
    try:
        shutil.copy2(cookie_path, temp_cookie)
    except Exception as e:
        print(f"Failed to copy cookies database: {e}")
        return None

    try:
        # Connect to the copied database
        conn = sqlite3.connect(temp_cookie)
        cursor = conn.cursor()

        # Query for YouTube cookies
        # Note: Chrome encrypts cookies on Linux/macOS, but on Windows they're not encrypted
        # For simplicity, we'll assume Windows here or that user has decryption setup
        cursor.execute("""
            SELECT name, value, host_key, path, expires_utc, is_secure, is_httponly
            FROM cookies
            WHERE host_key LIKE '%youtube%' OR host_key LIKE '%google%'
        """)

        cookies = cursor.fetchall()
        conn.close()

        # Write to Netscape cookie file format
        cookies_file = "cookies.txt"
        with open(cookies_file, 'w', encoding='utf-8') as f:
            f.write('# Netscape HTTP Cookie File\n')
            f.write('# https://curl.haxx.se/rfc/cookie_spec.html\n')
            f.write('# This file was generated by ytp.py\n')
            f.write('\n')

            for name, value, host_key, path, expires_utc, is_secure, is_httponly in cookies:
                # Convert Chrome timestamp to unix timestamp
                # Chrome uses microseconds since Jan 1, 1601 UTC
                # Unix time is seconds since Jan 1, 1970 UTC
                if expires_utc > 0:
                    expires = (expires_utc // 1000000) - 11644473600
                else:
                    expires = 0  # Session cookie

                secure_flag = "TRUE" if is_secure else "FALSE"
                httponly_flag = "TRUE" if is_httponly else "FALSE"

                f.write(f"{host_key}\t{secure_flag}\t{path}\t{httponly_flag}\t{expires}\t{name}\t{value}\n")

        print(f"Cookies extracted to {cookies_file}")
        return cookies_file

    except Exception as e:
        print(f"Error extracting cookies: {e}")
        return None
    finally:
        # Clean up temp file
        if os.path.exists(temp_cookie):
            os.remove(temp_cookie)

def main():
    if len(sys.argv) < 2:
        print("Usage: python ytp.py <YouTube_URL>")
        print("Example: python ytp.py https://www.youtube.com/watch?v=...")
        sys.exit(1)

    link = str(sys.argv[1])

    # Extract cookies
    cookies_file = get_chrome_cookies()

    # Configure yt_dlp options
    ydl_opts = {
        'format': 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best',
        'merge_output_format': 'mp4',
        'outtmpl': '%(title)s.%(ext)s',
    }

    # Add cookies if we successfully extracted them
    if cookies_file and os.path.exists(cookies_file):
        ydl_opts['cookiefile'] = cookies_file
        print("Using cookies for authentication")
    else:
        print("Warning: No cookies found. Some videos may require login.")

    # Download the video
    try:
        with yt_dlp.YoutubeDL(ydl_opts) as yt:
            yt.download([link])
        print("Success")
    except Exception as e:
        print(f"Download failed: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()